package.json, src/LollipopPlot.tsx, src/LollipopPlotNoTooltip.tsx, yarn.lock
- Updated package dependencies
- Added typings directory
=> Using cbioportal-frontend-commons instead of cbioportal-frontend-core

src/HotspotInfo.tsx
Related to https://github.com/cBioPortal/cbioportal-frontend/pull/2469
=> Use https for cancerhotspots links

src/LollipopMutationPlot.tsx, src/LollipopMutationPlotControls.tsx, src/TrackPanel.tsx, src/TrackSelector.tsx
=> Added options to customize lollipop plot controls

src/MutationMapper.tsx, src/component/oncokb/OncoKbTreatmentTable.tsx, src/store/DefaultMutationMapperStore.ts
=> Added support for custom mutation count

package.json, src/MutationMapper.tsx, src/util/DefaultWindowInstance.ts, yarn.lock
=> Made lollipop plot horizontally responsive

package.json, src/MutationMapper.tsx, src/component/ColumnSelector.tsx, src/component/FilterResetPanel.tsx, src/component/filterResetPanel.module.scss, src/index.tsx, src/model/DataStore.ts, src/store/DefaultMutationMapperDataStore.ts
=> Added filter reset panel

package.json, src/DefaultMutationTable.tsx, src/MutationMapper.tsx, src/PtmReferenceList.tsx, src/cache/DefaultPubMedCache.ts, src/component/oncokb/ReferenceList.tsx
=> Added a default pubmed cache

src/LollipopMutationPlot.tsx, src/MutationMapper.tsx, src/util/MutationUtils.ts
=> Using custom mutation count function when deciding the mutation color

package.json, src/Lollipop.tsx, src/LollipopMutationPlot.tsx, src/LollipopMutationPlotControls.tsx, src/LollipopPlot.tsx, src/LollipopPlotNoTooltip.tsx, src/MutationMapper.tsx, src/model/DataFilter.ts, src/model/DataStore.ts, src/model/LollipopSpec.ts, src/model/MutationFilter.ts, src/model/MutationMapperStore.ts, src/store/DefaultMutationMapperDataStore.ts, src/store/DefaultMutationMapperStore.ts, src/util/LollipopPlotUtils.ts
=> Added support for plotting lollipops below y-axis

src/DataTable.tsx
=> Hiding empty rows upon filtering

package.json, src/component/oncokb/OncoKBSuggestAnnotationLinkout.tsx, src/component/oncokb/oncokb.scss
Fix https://github.com/cBioPortal/cbioportal/issues/6470
=> Removed an incorrect reference to a redundant style

package.json, src/DataTable.tsx, src/DefaultMutationTable.tsx, src/HotspotTrack.tsx, src/MutationMapper.tsx, src/OncoKbTrack.tsx, src/Track.tsx, src/component/filter/DropdownSelector.tsx, src/component/filter/ProteinImpactTypeSelector.tsx, src/component/toolbar/DataTableToolbar.tsx, src/component/toolbar/SearchBox.tsx, src/filter/CancerTypeFilter.ts, src/filter/HotspotFilter.ts, src/filter/MutationFilter.ts, src/filter/OncoKbFilter.ts, src/filter/PositionFilter.ts, src/filter/ProteinImpactTypeFilter.ts, src/index.tsx, src/model/DataFilter.ts, src/model/DataStore.ts, src/model/FilterApplier.ts, src/model/HotspotFilter.ts, src/model/MutationFilter.ts, src/model/OncoKbFilter.ts, src/store/DefaultMutationMapperDataStore.ts, src/store/DefaultMutationMapperFilterApplier.ts, src/store/DefaultMutationMapperStore.ts, src/util/FilterUtils.ts, yarn.lock
- Simplified `DataFilter` interface and logic
- Added a free-form search box for the data table
- Added a basic dropdown UI for filters
=> Simplified data filters and added free text filtering

package.json, src/DefaultMutationTable.tsx, src/MutationMapper.tsx, src/component/column/Gnomad.tsx, src/component/gnomad/GnomadFrequency.tsx, src/component/gnomad/GnomadFrequencyTable.tsx, src/component/gnomad/gnomadFrequencyTable.scss, src/index.tsx, src/model/GnomadSummary.ts, src/model/MutationMapperStore.ts, src/store/DefaultMutationMapperDataFetcher.ts, src/store/DefaultMutationMapperStore.ts, src/util/MutationAnnotator.ts, src/util/VariantAnnotationUtils.ts, yarn.lock
Do not merge before merging (and publishing) cBioPortal/cbioportal-frontend/pull/2601
=> Added gnomad column

src/component/filter/DropdownSelector.tsx
Added a boolean parameter for `onSelect` prop to indicate whether all values are selected
=> Improved DropdownSelector onSelect prop

rollup.config.ts
Added options to fix broken rollup watch mode on certain systems.
=> Added watch options to rollup config

package.json, src/LollipopMutationPlot.tsx, src/MutationMapper.tsx, src/model/LollipopPlotControlsConfig.ts, src/store/DefaultLollipopPlotControlsConfig.ts
This allows to update certain values outside of lollipop plot
=> Added LollipopPlotControlsConfig

src/LollipopMutationPlot.tsx, src/LollipopMutationPlotControls.tsx, src/LollipopPlot.tsx, src/LollipopPlotNoTooltip.tsx, src/MutationMapper.tsx
implement https://github.com/cBioPortal/cbioportal/issues/6618
=> options for hiding y axis, hiding track selector, set plot height

src/LollipopMutationPlotControls.tsx, src/util/FormatUtils.ts
=> Always formatting slider input box value

package.json, src/LollipopMutationPlot.tsx, src/LollipopMutationPlotControls.tsx, src/util/LollipopPlotUtils.ts
=> Same initial scale for both top and bottom y axes

src/model/FilterApplier.ts, src/model/MutationMapperStore.ts, src/store/DefaultMutationMapperDataStore.ts, src/store/DefaultMutationMapperStore.ts
- updated `FilterApplier` function definition
- added default type definition for certain remote data
=> Minor type improvements

src/util/DataFetcherUtils.ts
This is to get latest default URL fix for oncokb API client
=> master to release-0.3.0

src/DefaultMutationTable.tsx, src/MutationMapper.tsx, src/component/column/Gnomad.tsx, src/component/column/MyVariantInfoHelper.tsx, src/component/gnomad/GnomadFrequency.tsx, src/util/VariantAnnotationUtils.ts
see cBioPortal/cbioportal-frontend/pull/2840
=> Fixed Gnomad url

package.json, src/component/oncokb/OncoKB.spec.tsx, src/test.ts, src/util/CancerHotspotsUtils.spec.ts, src/util/LollipopPlotUtils.spec.ts, src/util/MutationAnnotator.spec.ts, src/util/MutationUtils.spec.ts, src/util/MutationUtils.ts, src/util/PfamUtils.spec.ts, yarn.lock
Fix #9
Currently there is a canvas related issue which causes `LollipopPlotUtils` tests to fail: https://stackoverflow.com/questions/33269093/how-to-add-canvas-support-to-my-tests-in-jest
=> Made tests compatible with Jest

package.json, src/component/mutationMapper/GeneSummary.tsx, src/component/mutationMapper/MutationMapper.tsx
Related to cBioPortal/cbioportal/issues/6828
=> Made the transcript summary URL configurable for the gene summary panel

package.json, src/component/filter/BadgeSelector.tsx, src/component/filter/ProteinImpactTypeBadgeSelector.tsx, yarn.lock
Related to cBioPortal/cbioportal/issues/6883
=> Added an option to enable special click behavior for the protein impact type selector

package.json
=> Updated version to 0.3.6
